package com.nas.naswebdav.smarttools

import android.content.Context
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.nas.naswebdav.NasApplication
import com.nas.naswebdav.OrganizerGroup
import com.nas.naswebdav.ThumbnailAuditData
import com.nas.naswebdav.OrganizerFilter
import com.nas.naswebdav.WebDavManager
import com.nas.naswebdav.WebDavRepository
import com.nas.naswebdav.toApiBaseUrl
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaTypeOrNull
import okhttp3.RequestBody.Companion.toRequestBody

/**
 * SmartToolsViewModel — Phase 2 của VM Split.
 *
 * Quản lý: Duplicate scan (18 vars), Thumbnail generation, Smart organizer.
 *
 * Constructor: (repository) — WebDavManager là singleton, dùng trực tiếp.
 *
 * Phase 2 skeleton: state declarations + placeholder methods.
 * Function bodies sẽ được move từ facade trong Phase 2b (commits tiếp theo).
 * Before that, UI files continue reading state from WebDavViewModel facade.
 */
class SmartToolsViewModel(
    private val repository: WebDavRepository
) : ViewModel() {

    // ═══ DUPLICATE SCAN STATE ═══

    var isShowingDuplicates by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var shouldAutoOpenDuplicates by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var duplicateFilesList by androidx.compose.runtime.mutableStateOf<List<com.nas.naswebdav.NasFile>>(emptyList())
        internal set
    val selectedDuplicates = androidx.compose.runtime.mutableStateListOf<com.nas.naswebdav.NasFile>()
    var isScanningDuplicates by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var isWorkerRunning by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var scanJob: kotlinx.coroutines.Job? = null
        internal set

    var scanDuplicatesCurrentFolderUrl by androidx.compose.runtime.mutableStateOf("")
        internal set
    var scanDuplicatesCurrentItemName by androidx.compose.runtime.mutableStateOf("")
        internal set
    var scanDuplicatesTotalScanned by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var scanDuplicatesFound by androidx.compose.runtime.mutableIntStateOf(0)
    var scanDuplicatesPercent by androidx.compose.runtime.mutableFloatStateOf(0f)
    var scanDuplicatesCurrentStagePercent by androidx.compose.runtime.mutableFloatStateOf(0f)
    var scanDuplicatesElapsedTime by androidx.compose.runtime.mutableLongStateOf(0L)
    var scanDuplicatesEstimatedTimeRemaining by androidx.compose.runtime.mutableLongStateOf(-1L)
    var scanDuplicatesIsFolder by androidx.compose.runtime.mutableStateOf(false)
    var scanDuplicatesStage by androidx.compose.runtime.mutableStateOf("Khởi động...")
    var scanDuplicatesStageNumber by androidx.compose.runtime.mutableIntStateOf(1)
    var scanDuplicatesTotalStages by androidx.compose.runtime.mutableIntStateOf(4)
    var scanDuplicatesStageDescription by androidx.compose.runtime.mutableStateOf("")
    var scanDuplicatesIsPaused by androidx.compose.runtime.mutableStateOf(false)
    var autoCleanEnabled by androidx.compose.runtime.mutableStateOf(false)

    // ═══ THUMBNAIL GENERATION STATE ═══

    var thumbGenerated by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var thumbTotal by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var thumbErrors by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var thumbRunning by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var thumbLastFile by androidx.compose.runtime.mutableStateOf("")
        internal set
    var thumbElapsed by androidx.compose.runtime.mutableLongStateOf(0L)
        internal set
    var thumbEta by androidx.compose.runtime.mutableLongStateOf(-1L)
        internal set
    var thumbElapsedFmt by androidx.compose.runtime.mutableStateOf("")
        internal set
    var thumbEtaFmt by androidx.compose.runtime.mutableStateOf("")
        internal set
    var thumbPaused by androidx.compose.runtime.mutableStateOf(false)
        internal set
    internal val _thumbnailAudit = kotlinx.coroutines.flow.MutableStateFlow(ThumbnailAuditData())
    val thumbnailAudit: kotlinx.coroutines.flow.StateFlow<ThumbnailAuditData>
        get() = _thumbnailAudit

    // ═══ SMART ORGANIZER STATE ═══

    var organizerScanning by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var organizerExecuting by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var organizerScanResult by androidx.compose.runtime.mutableStateOf<List<OrganizerGroup>?>(null)
        internal set
    var organizerTotalFiles by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var organizerResult by androidx.compose.runtime.mutableStateOf<String?>(null)
        internal set
    var organizerError by androidx.compose.runtime.mutableStateOf<String?>(null)
        internal set
    var organizingLegacyRunning by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var organizingLegacyResult by androidx.compose.runtime.mutableStateOf<String?>(null)
        internal set

    // ═══ PLACEHOLDER METHODS — implement Phase 2b ═══

    fun startScanDuplicates() { /* TODO Phase 2b */ }
    fun cancelScanDuplicates() { /* TODO Phase 2b */ }
    fun toggleAutoClean(context: Context, enabled: Boolean) { /* TODO Phase 2b */ }
    fun dismissDuplicatesView() { isShowingDuplicates = false }
    fun resetShouldAutoOpenDuplicates() { shouldAutoOpenDuplicates = false }
    fun deleteDuplicateFile(file: com.nas.naswebdav.NasFile, index: Int) { /* TODO Phase 2b */ }
    fun deleteSelectedDuplicates(files: List<com.nas.naswebdav.NasFile>) { /* TODO Phase 2b */ }
    fun togglePauseDuplicateScan() { /* TODO Phase 2b */ }
    fun cancelDuplicateScan(context: android.content.Context) { /* TODO Phase 2b */ }

    fun triggerSmartOrganizeScan() { /* TODO Phase 2b */ }
    fun executeSmartOrganize(action: String = "move") { /* TODO Phase 2b */ }
    fun resetSmartOrganize() { organizerScanResult = null; organizerError = null; organizerResult = null }

    fun fetchThumbStatus() {
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val request = okhttp3.Request.Builder().url("${WebDavManager.currentBaseUrl.toApiBaseUrl()}/api/thumb/status").build()
                NasApplication.instance.fastApiClient.newBuilder().readTimeout(10, java.util.concurrent.TimeUnit.SECONDS).build()
                    .newCall(request).execute().use { response ->
                    if (response.isSuccessful) {
                        val json = org.json.JSONObject(response.body?.string() ?: "{}")
                        withContext(Dispatchers.Main) {
                            thumbGenerated = json.optInt("generated", 0)
                            thumbTotal = json.optInt("total_media", 0)
                            thumbErrors = json.optInt("errors", 0)
                            thumbRunning = json.optBoolean("running", false)
                            thumbPaused = json.optBoolean("paused", false)
                            thumbLastFile = json.optString("last_file", "")
                            thumbElapsed = json.optInt("elapsed_seconds", 0).toLong()
                            thumbEta = json.optInt("eta_seconds", -1).toLong()
                            thumbElapsedFmt = json.optString("elapsed_fmt", "00:00")
                            thumbEtaFmt = json.optString("eta_fmt", "--:--")
                        }
                    }
                }
            } catch (e: Exception) { android.util.Log.w("SmartToolsVM", "fetchThumbStatus: ${e.message}") }
        }
    }

    fun stopThumbGeneration() {
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val request = okhttp3.Request.Builder().url("${WebDavManager.currentBaseUrl.toApiBaseUrl()}/api/thumb/stop").build()
                NasApplication.instance.fastApiClient.newCall(request).execute().use { }
            } catch (_: Exception) {}
            thumbRunning = false
        }
    }

    fun toggleThumbPause() {
        val action = if (thumbPaused) "resume" else "pause"
        thumbPaused = action == "pause"
        if (thumbPaused) thumbRunning = false
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val body = org.json.JSONObject().put("action", action).toString().toRequestBody("application/json".toMediaTypeOrNull())
                val request = okhttp3.Request.Builder().url("${WebDavManager.currentBaseUrl.toApiBaseUrl()}/api/thumb/control").post(body).build()
                NasApplication.instance.fastApiClient.newBuilder().readTimeout(30, java.util.concurrent.TimeUnit.SECONDS).build()
                    .newCall(request).execute().use { resp ->
                    if (!resp.isSuccessful) withContext(Dispatchers.Main) { thumbPaused = action != "pause" }
                }
                kotlinx.coroutines.delay(1500)
                fetchThumbStatus()
            } catch (e: Exception) { withContext(Dispatchers.Main) { thumbPaused = action != "pause" } }
        }
    }

    fun smartOrganizeScan(filter: OrganizerFilter) {
        viewModelScope.launch(Dispatchers.IO) {
            try {
                withContext(Dispatchers.Main) {
                    organizerScanning = true; organizerScanResult = null; organizerResult = null; organizerError = null
                }
                val apiBase = WebDavManager.currentBaseUrl.toApiBaseUrl()
                val filterStr = when (filter) { OrganizerFilter.IMAGE -> "image"; OrganizerFilter.VIDEO -> "video"; OrganizerFilter.ALL -> "all" }
                val body = org.json.JSONObject().apply { put("filter", filterStr) }.toString().toRequestBody("application/json".toMediaTypeOrNull())
                val request = okhttp3.Request.Builder().url("$apiBase/api/tools/smart_organize/scan").post(body).build()
                val scanClient = NasApplication.instance.fastApiClient.newBuilder().readTimeout(3, java.util.concurrent.TimeUnit.MINUTES).build()
                scanClient.newCall(request).execute().use { response ->
                    val responseBody = response.body?.string()
                    withContext(Dispatchers.Main) {
                        if (response.isSuccessful && responseBody != null) {
                            try {
                                val json = org.json.JSONObject(responseBody)
                                organizerTotalFiles = json.optInt("total", 0)
                                val groupsArr = json.optJSONArray("groups") ?: org.json.JSONArray()
                                val groups = mutableListOf<com.nas.naswebdav.OrganizerGroup>()
                                for (i in 0 until groupsArr.length()) {
                                    val g = groupsArr.getJSONObject(i)
                                    val samples = mutableListOf<String>()
                                    val sf = g.optJSONArray("sample_files") ?: org.json.JSONArray()
                                    for (j in 0 until sf.length()) samples.add(sf.getJSONObject(j).optString("name", ""))
                                    groups.add(com.nas.naswebdav.OrganizerGroup(label = g.optString("label", "?"), count = g.optInt("count", 0), size = g.optLong("size", 0L), sampleFiles = samples))
                                }
                                organizerScanResult = groups
                            } catch (e: Exception) { organizerError = "Lỗi phân tích: ${e.message}" }
                        } else { organizerError = "Lỗi NAS: ${response.code}" }
                    }
                }
            } catch (e: Exception) { withContext(Dispatchers.Main) { organizerError = "Lỗi kết nối: ${e.message}" } }
            finally { withContext(Dispatchers.Main) { organizerScanning = false } }
        }
    }

    fun smartOrganizeExecute(filter: OrganizerFilter) {
        viewModelScope.launch(Dispatchers.IO) {
            try {
                withContext(Dispatchers.Main) { organizerExecuting = true; organizerResult = null; organizerError = null }
                val apiBase = WebDavManager.currentBaseUrl.toApiBaseUrl()
                val filterStr = when (filter) { OrganizerFilter.IMAGE -> "image"; OrganizerFilter.VIDEO -> "video"; OrganizerFilter.ALL -> "all" }
                val body = org.json.JSONObject().apply { put("filter", filterStr) }.toString().toRequestBody("application/json".toMediaTypeOrNull())
                val request = okhttp3.Request.Builder().url("$apiBase/api/tools/smart_organize/execute").post(body).build()
                val execClient = NasApplication.instance.fastApiClient.newBuilder().readTimeout(30, java.util.concurrent.TimeUnit.SECONDS).callTimeout(30, java.util.concurrent.TimeUnit.SECONDS).build()
                execClient.newCall(request).execute().use { response ->
                    val responseBody = response.body?.string() ?: throw Exception("Empty response body")
                    val json = org.json.JSONObject(responseBody)
                    val queued = response.code == 202 || json.optBoolean("queued", false)
                    if (queued) {
                        val jobId = json.optString("job_id", "")
                        if (jobId.isEmpty()) throw Exception("Missing job_id")
                        withContext(Dispatchers.Main) { organizerResult = "Đang sắp xếp..."; organizerScanResult = null }
                        val finalJson = pollSmartOrganizeJob(apiBase, jobId)
                        val finalStatus = finalJson.optString("status", "")
                        val movedCount = finalJson.optInt("moved_count", 0)
                        val errorCount = finalJson.optInt("error_count", 0)
                        val errorMessage = finalJson.optString("error", "")
                        withContext(Dispatchers.Main) {
                            organizerResult = when (finalStatus) {
                                "finished" -> "Hoàn tất — $movedCount tệp đã sắp xếp"
                                "finished_with_errors" -> "Hoàn tất — $movedCount tệp ($errorCount lỗi)"
                                else -> if (errorMessage.isNotEmpty()) errorMessage else "Smart Organizer thất bại"
                            }
                            if (finalStatus == "failed" || finalStatus == "aborted") { organizerError = organizerResult; organizerResult = null }
                            organizerScanResult = null
                        }
                    } else if (response.isSuccessful) {
                        withContext(Dispatchers.Main) { organizerResult = "Hoàn tất — ${json.optInt("moved_count", 0)} tệp"; organizerScanResult = null }
                    } else { throw Exception("Lỗi NAS: ${response.code}") }
                }
            } catch (e: Exception) { withContext(Dispatchers.Main) { organizerError = "Lỗi kết nối: ${e.message}" } }
            finally { withContext(Dispatchers.Main) { organizerExecuting = false } }
        }
    }

    private suspend fun pollSmartOrganizeJob(apiBase: String, jobId: String): org.json.JSONObject {
        var delayMs = 1000L; val deadline = System.currentTimeMillis() + 20 * 60 * 1000L
        while (System.currentTimeMillis() < deadline) {
            val request = okhttp3.Request.Builder().url("$apiBase/api/tools/smart_organize/status/$jobId").get().build()
            NasApplication.instance.fastApiClient.newCall(request).execute().use { response ->
                val responseBody = response.body?.string()
                if (!response.isSuccessful || responseBody == null) throw Exception("Lỗi NAS: ${response.code}")
                val json = org.json.JSONObject(responseBody)
                when (json.optString("status", "")) {
                    "queued", "running" -> Unit
                    "finished", "finished_with_errors", "failed", "aborted" -> return json
                    else -> throw Exception("Trạng thái không hợp lệ")
                }
            }
            kotlinx.coroutines.delay(delayMs); delayMs = (delayMs * 2).coerceAtMost(5000L)
        }
        throw java.util.concurrent.TimeoutException("Smart organizer timed out")
    }

    fun organizeLegacyVideos() {
        viewModelScope.launch {
            // TODO Phase 2b
        }
    }
    fun resetOrganizingLegacy() { organizingLegacyRunning = false; organizingLegacyResult = null }
}