package com.nas.naswebdav.smarttools

import android.content.Context
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.nas.naswebdav.NasApplication
import com.nas.naswebdav.OrganizerGroup
import com.nas.naswebdav.ThumbnailAuditData
import com.nas.naswebdav.WebDavManager
import com.nas.naswebdav.WebDavRepository
import com.nas.naswebdav.toApiBaseUrl
import kotlinx.coroutines.launch

/**
 * SmartToolsViewModel — Phase 2 của VM Split.
 *
 * Quản lý: Duplicate scan (18 vars), Thumbnail generation, Smart organizer.
 *
 * Constructor: (repository) — WebDavManager là singleton, dùng trực tiếp.
 *
 * Phase 2 skeleton: state declarations + placeholder methods.
 * Function bodies sẽ được move từ facade trong Phase 2b (commits tiếp theo).
 * Before that, UI files continue reading state from WebDavViewModel facade.
 */
class SmartToolsViewModel(
    private val repository: WebDavRepository
) : ViewModel() {

    // ═══ DUPLICATE SCAN STATE ═══

    var isShowingDuplicates by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var shouldAutoOpenDuplicates by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var duplicateFilesList by androidx.compose.runtime.mutableStateOf<List<com.nas.naswebdav.NasFile>>(emptyList())
        internal set
    val selectedDuplicates = androidx.compose.runtime.mutableStateListOf<com.nas.naswebdav.NasFile>()
    var isScanningDuplicates by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var isWorkerRunning by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var scanJob: kotlinx.coroutines.Job? = null
        internal set

    var scanDuplicatesCurrentFolderUrl by androidx.compose.runtime.mutableStateOf("")
        internal set
    var scanDuplicatesCurrentItemName by androidx.compose.runtime.mutableStateOf("")
        internal set
    var scanDuplicatesTotalScanned by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var scanDuplicatesFound by androidx.compose.runtime.mutableIntStateOf(0)
    var scanDuplicatesPercent by androidx.compose.runtime.mutableFloatStateOf(0f)
    var scanDuplicatesCurrentStagePercent by androidx.compose.runtime.mutableFloatStateOf(0f)
    var scanDuplicatesElapsedTime by androidx.compose.runtime.mutableLongStateOf(0L)
    var scanDuplicatesEstimatedTimeRemaining by androidx.compose.runtime.mutableLongStateOf(-1L)
    var scanDuplicatesIsFolder by androidx.compose.runtime.mutableStateOf(false)
    var scanDuplicatesStage by androidx.compose.runtime.mutableStateOf("Khởi động...")
    var scanDuplicatesStageNumber by androidx.compose.runtime.mutableIntStateOf(1)
    var scanDuplicatesTotalStages by androidx.compose.runtime.mutableIntStateOf(4)
    var scanDuplicatesStageDescription by androidx.compose.runtime.mutableStateOf("")
    var scanDuplicatesIsPaused by androidx.compose.runtime.mutableStateOf(false)
    var autoCleanEnabled by androidx.compose.runtime.mutableStateOf(false)

    // ═══ THUMBNAIL GENERATION STATE ═══

    var thumbGenerated by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var thumbTotal by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var thumbErrors by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var thumbRunning by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var thumbLastFile by androidx.compose.runtime.mutableStateOf("")
        internal set
    var thumbElapsed by androidx.compose.runtime.mutableLongStateOf(0L)
        internal set
    var thumbEta by androidx.compose.runtime.mutableLongStateOf(-1L)
        internal set
    var thumbElapsedFmt by androidx.compose.runtime.mutableStateOf("")
        internal set
    var thumbEtaFmt by androidx.compose.runtime.mutableStateOf("")
        internal set
    var thumbPaused by androidx.compose.runtime.mutableStateOf(false)
        internal set
    internal val _thumbnailAudit = kotlinx.coroutines.flow.MutableStateFlow(ThumbnailAuditData())
    val thumbnailAudit: kotlinx.coroutines.flow.StateFlow<ThumbnailAuditData>
        get() = _thumbnailAudit

    // ═══ SMART ORGANIZER STATE ═══

    var organizerScanning by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var organizerExecuting by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var organizerScanResult by androidx.compose.runtime.mutableStateOf<List<OrganizerGroup>?>(null)
        internal set
    var organizerTotalFiles by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var organizerResult by androidx.compose.runtime.mutableStateOf<String?>(null)
        internal set
    var organizerError by androidx.compose.runtime.mutableStateOf<String?>(null)
        internal set
    var organizingLegacyRunning by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var organizingLegacyResult by androidx.compose.runtime.mutableStateOf<String?>(null)
        internal set

    // ═══ PLACEHOLDER METHODS — implement Phase 2b ═══

    fun startScanDuplicates() { /* TODO Phase 2b */ }
    fun cancelScanDuplicates() { /* TODO Phase 2b */ }
    fun togglePauseDuplicateScan() { /* TODO Phase 2b */ }
    fun toggleAutoClean(context: Context, enabled: Boolean) { /* TODO Phase 2b */ }
    fun dismissDuplicatesView() { isShowingDuplicates = false }
    fun deleteDuplicateFile(file: com.nas.naswebdav.NasFile, index: Int) { /* TODO Phase 2b */ }
    fun deleteSelectedDuplicates(files: List<com.nas.naswebdav.NasFile>) { /* TODO Phase 2b */ }

    fun startThumbnailScan() { /* TODO Phase 2b */ }
    fun stopThumbnailGeneration() { /* TODO Phase 2b */ }
    fun toggleThumbPause() { /* TODO Phase 2b */ }
    fun fetchThumbnailAudit() { /* TODO Phase 2b */ }

    fun triggerSmartOrganizeScan() { /* TODO Phase 2b */ }
    fun executeSmartOrganize(action: String = "move") { /* TODO Phase 2b */ }
    fun resetSmartOrganize() { organizerScanResult = null; organizerError = null; organizerResult = null }

    fun organizeLegacyVideos() {
        viewModelScope.launch {
            // TODO Phase 2b
        }
    }
    fun resetOrganizingLegacy() { organizingLegacyRunning = false; organizingLegacyResult = null }
}