package com.nas.naswebdav.smarttools

import android.content.Context
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.nas.naswebdav.NasApplication
import com.nas.naswebdav.DuplicateProgressState
import com.nas.naswebdav.OrganizerGroup
import com.nas.naswebdav.ThumbnailAuditData
import com.nas.naswebdav.OrganizerFilter
import com.nas.naswebdav.WebDavManager
import com.nas.naswebdav.WebDavRepository
import com.nas.naswebdav.AutoDuplicateScanWorker
import com.nas.naswebdav.DuplicateScanWorker
import com.nas.naswebdav.toApiBaseUrl
import com.nas.naswebdav.buildWebDavTrashTargetUrl
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaTypeOrNull
import okhttp3.RequestBody.Companion.toRequestBody
import androidx.core.content.edit

/**
 * SmartToolsViewModel — Primary owner of smart-tools state.
 *
 * Quản lý: Duplicate scan, Thumbnail generation, Smart organizer.
 *
 * Constructor: (repository) — WebDavManager là singleton, dùng trực tiếp.
 *
 * Phase 2: initial skeleton. Phase 7d.x: migrated from WebDavViewModel facade.
 * UI now reads state directly from this VM.
 */
class SmartToolsViewModel(
    private val repository: WebDavRepository
) : ViewModel() {

    // ═══ DUPLICATE SCAN STATE ═══

    var isShowingDuplicates by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var shouldAutoOpenDuplicates by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var duplicateFilesList by androidx.compose.runtime.mutableStateOf<List<com.nas.naswebdav.NasFile>>(emptyList())
        internal set
    val selectedDuplicates = androidx.compose.runtime.mutableStateListOf<com.nas.naswebdav.NasFile>()
    var isScanningDuplicates by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var isWorkerRunning by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var scanJob: kotlinx.coroutines.Job? = null
        internal set

    var scanDuplicatesCurrentFolderUrl by androidx.compose.runtime.mutableStateOf("")
        internal set
    var scanDuplicatesCurrentItemName by androidx.compose.runtime.mutableStateOf("")
        internal set
    var scanDuplicatesTotalScanned by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var scanDuplicatesFound by androidx.compose.runtime.mutableIntStateOf(0)
    var scanDuplicatesPercent by androidx.compose.runtime.mutableFloatStateOf(0f)
    var scanDuplicatesCurrentStagePercent by androidx.compose.runtime.mutableFloatStateOf(0f)
    var scanDuplicatesElapsedTime by androidx.compose.runtime.mutableLongStateOf(0L)
    var scanDuplicatesEstimatedTimeRemaining by androidx.compose.runtime.mutableLongStateOf(-1L)
    var scanDuplicatesIsFolder by androidx.compose.runtime.mutableStateOf(false)
    var scanDuplicatesStage by androidx.compose.runtime.mutableStateOf("Khởi động...")
    var scanDuplicatesStageNumber by androidx.compose.runtime.mutableIntStateOf(1)
    var scanDuplicatesTotalStages by androidx.compose.runtime.mutableIntStateOf(4)
    var scanDuplicatesStageDescription by androidx.compose.runtime.mutableStateOf("")
    var scanDuplicatesIsPaused by androidx.compose.runtime.mutableStateOf(false)
    var autoCleanEnabled by androidx.compose.runtime.mutableStateOf(false)

    // ═══ THUMBNAIL GENERATION STATE ═══

    var thumbGenerated by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var thumbTotal by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var thumbErrors by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var thumbRunning by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var thumbLastFile by androidx.compose.runtime.mutableStateOf("")
        internal set
    var thumbElapsed by androidx.compose.runtime.mutableLongStateOf(0L)
        internal set
    var thumbEta by androidx.compose.runtime.mutableLongStateOf(-1L)
        internal set
    var thumbElapsedFmt by androidx.compose.runtime.mutableStateOf("")
        internal set
    var thumbEtaFmt by androidx.compose.runtime.mutableStateOf("")
        internal set
    var thumbPaused by androidx.compose.runtime.mutableStateOf(false)
        internal set
    internal val _thumbnailAudit = kotlinx.coroutines.flow.MutableStateFlow(ThumbnailAuditData())
    val thumbnailAudit: kotlinx.coroutines.flow.StateFlow<ThumbnailAuditData>
        get() = _thumbnailAudit

    // ═══ SMART ORGANIZER STATE ═══

    var organizerScanning by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var organizerExecuting by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var organizerScanResult by androidx.compose.runtime.mutableStateOf<List<OrganizerGroup>?>(null)
        internal set
    var organizerTotalFiles by androidx.compose.runtime.mutableIntStateOf(0)
        internal set
    var organizerResult by androidx.compose.runtime.mutableStateOf<String?>(null)
        internal set
    var organizerError by androidx.compose.runtime.mutableStateOf<String?>(null)
        internal set
    var organizingLegacyRunning by androidx.compose.runtime.mutableStateOf(false)
        internal set
    var organizingLegacyResult by androidx.compose.runtime.mutableStateOf<String?>(null)
        internal set

    var globalUi: com.nas.naswebdav.GlobalUiViewModel? = null
        private set

    fun attachGlobalUi(ui: com.nas.naswebdav.GlobalUiViewModel) {
        globalUi = ui
    }

    private val _globalUi: com.nas.naswebdav.GlobalUiViewModel
        get() = globalUi ?: fallbackGlobalUi

    private val fallbackGlobalUi by lazy {
        com.nas.naswebdav.GlobalUiViewModel()
    }

    // ═══ AUTO CLEAN ═══

    fun toggleAutoClean(context: Context, enabled: Boolean) {
        autoCleanEnabled = enabled
        // R3-P2: ghi qua PreferencesRepository để snapshot StateFlow cập nhật —
        // bản cũ ghi SharedPreferences trực tiếp, BrowserScreen đọc snapshot cũ
        // nên công tắc hiện tắt dù WorkManager vẫn chạy.
        com.nas.naswebdav.utils.PreferencesRepository.get(context).setAutoCleanEnabled(enabled)
        val workManager = androidx.work.WorkManager.getInstance(context)
        if (enabled) {
            val constraints = androidx.work.Constraints.Builder()
                .setRequiresCharging(true)
                .setRequiredNetworkType(androidx.work.NetworkType.UNMETERED)
                .build()
            val req = androidx.work.PeriodicWorkRequestBuilder<AutoDuplicateScanWorker>(
                30, java.util.concurrent.TimeUnit.DAYS)
                .setConstraints(constraints)
                .setBackoffCriteria(
                    androidx.work.BackoffPolicy.EXPONENTIAL,
                    30,
                    java.util.concurrent.TimeUnit.SECONDS
                )
                .build()
            workManager.enqueueUniquePeriodicWork(
                "AutoCleanDuplicates", androidx.work.ExistingPeriodicWorkPolicy.UPDATE, req)
        } else {
            workManager.cancelUniqueWork("AutoCleanDuplicates")
        }
    }

    // ═══ BACKGROUND DUPLICATE SCAN ═══

    fun startBackgroundDuplicateScan(context: Context, forceRestart: Boolean = false, lightningMode: Boolean = true) {
        _globalUi.show(com.nas.naswebdav.ui.dialogs.DialogType.SUCCESS,
            "Đã nhận lệnh! Đang khởi động trình quét rác...")
        isScanningDuplicates = true
        viewModelScope.launch {
            repository.addSystemLog("INFO", "DuplicateScan",
                "Hệ thống: Người dùng đã phân công quét thủ công trùng lặp")
        }
        if (isWorkerRunning) return

        isWorkerRunning = true
        scanDuplicatesCurrentFolderUrl = "Đang kết nối..."
        scanDuplicatesCurrentItemName = "Khởi tạo..."
        scanDuplicatesTotalScanned = 0
        scanDuplicatesFound = 0
        scanDuplicatesStage = "Khởi động..."

        scanJob?.cancel()
        scanJob = viewModelScope.launch(Dispatchers.Main) {
            kotlinx.coroutines.delay(500)
            try {
                val workManager = androidx.work.WorkManager.getInstance(context)
                val currentUrl = com.nas.naswebdav.WebDavManager.currentBaseUrl
                val inputData = androidx.work.workDataOf(
                    "currentUrl" to currentUrl,
                    "forceRestart" to forceRestart,
                    "lightningMode" to lightningMode
                )
                val scanWorkRequest = androidx.work.OneTimeWorkRequestBuilder<DuplicateScanWorker>()
                    .setInputData(inputData)
                    .build()
                workManager.enqueueUniqueWork("Unique_Scan_V3",
                    androidx.work.ExistingWorkPolicy.REPLACE, scanWorkRequest)

                workManager.getWorkInfoByIdFlow(scanWorkRequest.id).collect { workInfo ->
                    if (workInfo != null) {
                        when (workInfo.state) {
                            androidx.work.WorkInfo.State.SUCCEEDED -> {
                                scanDuplicatesStage = "Hoàn tất"
                                scanDuplicatesCurrentFolderUrl = "Hoàn tất!"
                                scanDuplicatesCurrentItemName = "Đã quét xong toàn bộ."
                                scanDuplicatesPercent = 1f
                                scanDuplicatesCurrentStagePercent = 1f
                                scanDuplicatesStageNumber = 4
                                scanDuplicatesStageDescription = "Đã quét xong toàn bộ."
                                isWorkerRunning = false
                                loadDuplicateResultsFromCache(context)
                            }
                            androidx.work.WorkInfo.State.FAILED -> {
                                scanDuplicatesCurrentFolderUrl = "Gặp lỗi hệ thống!"
                                isWorkerRunning = false
                            }
                            androidx.work.WorkInfo.State.CANCELLED -> {
                                isWorkerRunning = false
                            }
                            else -> { /* RUNNING, ENQUEUED, BLOCKED */ }
                        }
                    }
                }
            } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (e: Exception) {
                isWorkerRunning = false
            }
        }
    }

    fun loadDuplicateResultsFromCache(context: Context) {
        viewModelScope.launch {
            try {
                val duplicates = withContext(Dispatchers.IO) {
                    repository.getDuplicateFiles()
                }
                withContext(Dispatchers.Main) {
                    duplicateFilesList = duplicates
                    isShowingDuplicates = true
                }
            } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (e: Exception) {
                withContext(Dispatchers.Main) {
                    _globalUi.show(com.nas.naswebdav.ui.dialogs.DialogType.ERROR,
                        "Lỗi nạp danh sách từ DB: ${e.message}")
                }
            }
        }
    }

    // ═══ UNZIP ═══

    fun unzipFile(filePath: String) {
        val uri = java.net.URI(filePath)
        val relativePath = uri.path.substringAfter("/webdav")
        val fileName = filePath.substringAfterLast("/")
        val jsonBody = org.json.JSONObject().apply {
            put("file_path", relativePath)
        }.toString()

        _globalUi.show(com.nas.naswebdav.ui.dialogs.DialogType.SUCCESS,
            "Tác vụ giải nén ($fileName) đang chạy ngầm trên NAS!")

        val inputData = androidx.work.Data.Builder()
            .putString("taskType", "UNZIP")
            .putString("apiUrl",
                "${com.nas.naswebdav.WebDavManager.currentBaseUrl.toApiBaseUrl()}/api/file/unzip")
            .putString("jsonBody", jsonBody)
            .putString("taskLabel", "Giải nén $fileName")
            .build()
        val workRequest = androidx.work.OneTimeWorkRequestBuilder<com.nas.naswebdav.LongRunningApiWorker>()
            .setInputData(inputData)
            .addTag("LONG_RUNNING_API")
            .build()
        val context = NasApplication.instance.applicationContext
        androidx.work.WorkManager.getInstance(context).enqueue(workRequest)
    }
    fun dismissDuplicatesView() { isShowingDuplicates = false }
    fun resetShouldAutoOpenDuplicates() { shouldAutoOpenDuplicates = false }
    fun deleteDuplicateFile(file: com.nas.naswebdav.NasFile) {
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val isInTrash = file.path.contains(".trash")
                if (isInTrash) {
                    WebDavManager.deleteFile(file.path, file.isDirectory, WebDavManager.currentAuthState())
                    repository.removeDuplicateFromDb(file.path)
                } else {
                    val rootUrl = WebDavManager.currentBaseUrl.trimEnd('/')
                    val trashFolderUrl = buildWebDavTrashTargetUrl(rootUrl, file.path, "", false)
                    var trashTargetUrl = buildWebDavTrashTargetUrl(rootUrl, file.path, file.name, file.isDirectory)
                    try { WebDavManager.createFolder(trashFolderUrl) } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (_: Exception) {}
                    try {
                        try {
                            WebDavManager.renameFile(file.path, trashTargetUrl, WebDavManager.currentAuthState())
                        } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (e: Exception) {
                            // R2-P1: đích trash trùng tên (412 Overwrite F) → đổi tên
                            // duy nhất rồi thử lại, không ghi đè bản trash cũ.
                            val nm = file.name
                            val dot = nm.lastIndexOf('.')
                            val unique = if (dot > 0) {
                                nm.substring(0, dot) + "_" + System.currentTimeMillis() + nm.substring(dot)
                            } else {
                                nm + "_" + System.currentTimeMillis()
                            }
                            trashTargetUrl = buildWebDavTrashTargetUrl(rootUrl, file.path, unique, file.isDirectory)
                            WebDavManager.renameFile(file.path, trashTargetUrl, WebDavManager.currentAuthState())
                        }
                        try {
                            NasApplication.instance.database.trashMetaDao().insert(
                                com.nas.naswebdav.TrashMeta(trashPath = trashTargetUrl, originalPath = file.path)
                            )
                        } catch (_: Exception) {}
                    } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (moveEx: Exception) {
                        // FIX-REVIEW-S6: MOVE trash fail → GIỮ FILE, báo lỗi.
                        // Không fallback DELETE vĩnh viễn (user bấm xóa 1 file
                        // trong nhóm "trùng", mất là mất thật).
                        throw Exception("Không chuyển được vào trash, giữ nguyên file: ${moveEx.message}")
                    }
                    repository.removeDuplicateFromDb(file.path)
                }
                withContext(Dispatchers.Main) {
                    duplicateFilesList = duplicateFilesList.filter { it.path != file.path }
                    selectedDuplicates.remove(file)
                }
            } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (e: Exception) {
                android.util.Log.w("SmartToolsVM", "deleteDuplicateFile: ${e.message}")
            }
        }
    }

    /**
     * R2-P1: full-verify một nhóm trước khi MOVE hàng loạt vào trash.
     * UI group theo partial hash (1MB đầu) — hai file cùng đầu khác đuôi vẫn
     * chung nhóm. Verify full SHA-256 + byte count của TỪNG file, chỉ nhóm con
     * nào khớp toàn bộ mới cho xóa. File verify fail bị loại khỏi danh sách.
     * @return danh sách file đã xác minh trùng toàn bộ, rỗng nếu không có.
     */
    suspend fun verifyDuplicateGroup(paths: List<com.nas.naswebdav.NasFile>): List<com.nas.naswebdav.NasFile> =
        withContext(Dispatchers.IO) {
            if (paths.size < 2) return@withContext emptyList<com.nas.naswebdav.NasFile>()
            try {
                val hashes = mutableMapOf<String, String>()
                for (f in paths) {
                    val size = f.contentLength
                    val h = WebDavManager.getFullSha256PhoneStream(f.path, size)
                    if (h.isNullOrEmpty()) {
                        com.nas.naswebdav.utils.SystemLogger.log("WARNING", "DuplicateVerify",
                            "Loại khỏi nhóm xóa (không verify full được): ${f.name}")
                        continue
                    }
                    hashes[f.path] = h
                }
                val byHash = hashes.entries.groupBy({ it.value }, { it.key })
                    .filter { it.value.size > 1 }
                if (byHash.isEmpty()) return@withContext emptyList<com.nas.naswebdav.NasFile>()
                // Giữ lại 1 bản (đường ngắn nhất), trả các bản còn lại để xóa.
                val keep = byHash.values.flatten().minByOrNull { it.length } ?: return@withContext emptyList<com.nas.naswebdav.NasFile>()
                val toDelete = byHash.values.flatten().filter { it != keep }.toSet()
                paths.filter { it.path in toDelete }
            } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (e: Exception) {
                com.nas.naswebdav.utils.SystemLogger.log("WARNING", "DuplicateVerify",
                    "Verify nhóm thất bại, không xóa: ${e.message}")
                emptyList()
            }
        }

    fun deleteSelectedDuplicates(files: List<com.nas.naswebdav.NasFile>) {
        files.forEach { deleteDuplicateFile(it) }
    }

    /**
     * R2-P1: xóa cả nhóm SAU full-verify. UI gọi hàm này thay vì
     * deleteSelectedDuplicates khi user bấm "xóa nhóm trùng".
     */
    fun deleteVerifiedGroup(files: List<com.nas.naswebdav.NasFile>) {
        viewModelScope.launch(Dispatchers.IO) {
            val verified = verifyDuplicateGroup(files)
            if (verified.isEmpty()) {
                _globalUi.show(com.nas.naswebdav.ui.dialogs.DialogType.WARNING,
                    "Nhóm chưa xác minh trùng toàn bộ — không xóa để an toàn.")
                return@launch
            }
            verified.forEach { deleteDuplicateFile(it) }
        }
    }
    fun togglePauseDuplicateScan() {
        scanDuplicatesIsPaused = !scanDuplicatesIsPaused
        DuplicateProgressState.isPaused.value = scanDuplicatesIsPaused
    }

    fun cancelDuplicateScan(context: android.content.Context) {
        DuplicateProgressState.isPaused.value = false
        scanDuplicatesIsPaused = false
        androidx.work.WorkManager.getInstance(context).cancelUniqueWork("Unique_Scan_V3")
        isWorkerRunning = false
        scanJob?.cancel()
        isScanningDuplicates = false
        duplicateFilesList = emptyList()
        DuplicateProgressState.stage.value = "Khởi động..."
        DuplicateProgressState.percent.value = 0f
    }


    fun resetSmartOrganize() { organizerScanResult = null; organizerError = null; organizerResult = null }

    fun fetchThumbStatus() {
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val request = okhttp3.Request.Builder().url("${WebDavManager.currentBaseUrl.toApiBaseUrl()}/api/thumb/status").let(WebDavManager::tagCurrentAuth).build()
                // REVIEW-R6: dùng fastApiClient dùng chung — newBuilder() mỗi lần gọi
                // tạo pool/thread riêng không bao giờ đóng (leak mỗi lần resume).
                // Timeout qua withTimeout thay vì client riêng.
                kotlinx.coroutines.withTimeout(15_000L) {
                    NasApplication.instance.fastApiClient.newCall(request).execute().use { response ->
                    if (response.isSuccessful) {
                        val json = org.json.JSONObject(response.body?.string() ?: "{}")
                        withContext(Dispatchers.Main) {
                            thumbGenerated = json.optInt("generated", 0)
                            thumbTotal = json.optInt("total_media", 0)
                            thumbErrors = json.optInt("errors", 0)
                            thumbRunning = json.optBoolean("running", false)
                            thumbPaused = json.optBoolean("paused", false)
                            thumbLastFile = json.optString("last_file", "")
                            thumbElapsed = json.optInt("elapsed_seconds", 0).toLong()
                            thumbEta = json.optInt("eta_seconds", -1).toLong()
                            thumbElapsedFmt = json.optString("elapsed_fmt", "00:00")
                            thumbEtaFmt = json.optString("eta_fmt", "--:--")
                        }
                    }
                }
                }
            } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (e: Exception) { android.util.Log.w("SmartToolsVM", "fetchThumbStatus: ${e.message}") }
        }
    }

    fun stopThumbGeneration() {
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val json = org.json.JSONObject().put("action", "pause").toString()
                    .toRequestBody("application/json".toMediaTypeOrNull())
                val request = okhttp3.Request.Builder()
                    .url("${WebDavManager.currentBaseUrl.toApiBaseUrl()}/api/thumb/control")
                    .post(json).build()
                NasApplication.instance.fastApiClient.newCall(request).execute().use { }
            } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (_: Exception) {}
            withContext(Dispatchers.Main) { thumbRunning = false }
        }
    }

    fun toggleThumbPause() {
        val action = if (thumbPaused) "resume" else "pause"
        thumbPaused = action == "pause"
        if (thumbPaused) thumbRunning = false
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val body = org.json.JSONObject().put("action", action).toString().toRequestBody("application/json".toMediaTypeOrNull())
                val request = okhttp3.Request.Builder().url("${WebDavManager.currentBaseUrl.toApiBaseUrl()}/api/thumb/control").post(body).build()
                // REVIEW-R6: shared client + withTimeout (het leak pool moi lan goi).
                kotlinx.coroutines.withTimeout(35_000L) {
                    NasApplication.instance.fastApiClient.newCall(request).execute().use { resp ->
                    if (!resp.isSuccessful) withContext(Dispatchers.Main) { thumbPaused = action != "pause" }
                }
                }
                kotlinx.coroutines.delay(1500)
                fetchThumbStatus()
            } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (e: Exception) { withContext(Dispatchers.Main) { thumbPaused = action != "pause" } }
        }
    }

    fun fetchThumbnailAudit() {
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val apiBase = WebDavManager.currentBaseUrl.toApiBaseUrl()
                if (apiBase.isBlank()) return@launch
                val apiUrl = "$apiBase/api/thumb/status"
                val user = com.nas.naswebdav.SecurePrefsHelper.getUser(NasApplication.instance.applicationContext)
                val pass = com.nas.naswebdav.SecurePrefsHelper.getPass(NasApplication.instance.applicationContext)
                val request = okhttp3.Request.Builder()
                    .url(apiUrl)
                    .header("Authorization", WebDavManager.AuthState(user = user, pass = pass).authHeader)
                    .build()
                NasApplication.instance.fastApiClient.newCall(request).execute().use { response ->
                    if (response.isSuccessful) {
                        val body = response.body?.string() ?: "{}"
                        val obj = org.json.JSONObject(body)
                        val total = obj.optInt("total_media", 0)
                        val generated = obj.optInt("generated", 0)
                        _thumbnailAudit.value = ThumbnailAuditData(
                            total = total,
                            thumbnailed = generated,
                            missing = if (total > generated) total - generated else 0,
                            running = obj.optBoolean("running", false),
                            paused = obj.optBoolean("paused", false),
                            errors = obj.optInt("errors", 0)
                        )
                    }
                }
            } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (e: Exception) {
                android.util.Log.w("SmartToolsVM", "fetchThumbnailAudit failed", e)
            }
        }
    }

    fun triggerThumbnailScan() {
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val apiBase = WebDavManager.currentBaseUrl.toApiBaseUrl()
                if (apiBase.isBlank()) return@launch
                val apiUrl = "$apiBase/api/thumb/control"
                val user = com.nas.naswebdav.SecurePrefsHelper.getUser(NasApplication.instance.applicationContext)
                val pass = com.nas.naswebdav.SecurePrefsHelper.getPass(NasApplication.instance.applicationContext)
                val body = "{\"action\": \"resume\"}".toRequestBody("application/json".toMediaTypeOrNull())
                val request = okhttp3.Request.Builder()
                    .url(apiUrl)
                    .post(body)
                    .header("Authorization", WebDavManager.AuthState(user = user, pass = pass).authHeader)
                    .build()
                NasApplication.instance.fastApiClient.newCall(request).execute().use { }
                kotlinx.coroutines.delay(1000)
                fetchThumbnailAudit()
            } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (e: Exception) {
                android.util.Log.w("SmartToolsVM", "triggerThumbnailScan failed", e)
            }
        }
    }

    fun smartOrganizeScan(filter: OrganizerFilter) {
        viewModelScope.launch(Dispatchers.IO) {
            try {
                withContext(Dispatchers.Main) {
                    organizerScanning = true; organizerScanResult = null; organizerResult = null; organizerError = null
                }
                val apiBase = WebDavManager.currentBaseUrl.toApiBaseUrl()
                val filterStr = when (filter) { OrganizerFilter.IMAGE -> "image"; OrganizerFilter.VIDEO -> "video"; OrganizerFilter.ALL -> "all" }
                val body = org.json.JSONObject().apply { put("filter", filterStr) }.toString().toRequestBody("application/json".toMediaTypeOrNull())
                val request = okhttp3.Request.Builder().url("$apiBase/api/tools/smart_organize/scan").post(body).let(WebDavManager::tagCurrentAuth).build()
                kotlinx.coroutines.withTimeout(200_000L) {
                    NasApplication.instance.fastApiClient.newCall(request).execute().use { response ->
                    val responseBody = response.body?.string()
                    withContext(Dispatchers.Main) {
                        if (response.isSuccessful && responseBody != null) {
                            try {
                                val json = org.json.JSONObject(responseBody)
                                organizerTotalFiles = json.optInt("total", 0)
                                val groupsArr = json.optJSONArray("groups") ?: org.json.JSONArray()
                                val groups = mutableListOf<com.nas.naswebdav.OrganizerGroup>()
                                for (i in 0 until groupsArr.length()) {
                                    val g = groupsArr.getJSONObject(i)
                                    val samples = mutableListOf<String>()
                                    val sf = g.optJSONArray("sample_files") ?: org.json.JSONArray()
                                    for (j in 0 until sf.length()) samples.add(sf.getJSONObject(j).optString("name", ""))
                                    groups.add(com.nas.naswebdav.OrganizerGroup(label = g.optString("label", "?"), count = g.optInt("count", 0), size = g.optLong("size", 0L), sampleFiles = samples))
                                }
                                organizerScanResult = groups
                            } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (e: Exception) { organizerError = "Lỗi phân tích: ${e.message}" }
                        } else { organizerError = "Lỗi NAS: ${response.code}" }
                    }
                }
                }
            } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (e: Exception) { withContext(Dispatchers.Main) { organizerError = "Lỗi kết nối: ${e.message}" } }
            finally { withContext(Dispatchers.Main) { organizerScanning = false } }
        }
    }

    fun smartOrganizeExecute(filter: OrganizerFilter) {
        viewModelScope.launch(Dispatchers.IO) {
            try {
                withContext(Dispatchers.Main) { organizerExecuting = true; organizerResult = null; organizerError = null }
                val apiBase = WebDavManager.currentBaseUrl.toApiBaseUrl()
                val filterStr = when (filter) { OrganizerFilter.IMAGE -> "image"; OrganizerFilter.VIDEO -> "video"; OrganizerFilter.ALL -> "all" }
                val body = org.json.JSONObject().apply { put("filter", filterStr) }.toString().toRequestBody("application/json".toMediaTypeOrNull())
                val request = okhttp3.Request.Builder().url("$apiBase/api/tools/smart_organize/execute").post(body).let(WebDavManager::tagCurrentAuth).build()
                kotlinx.coroutines.withTimeout(35_000L) {
                    NasApplication.instance.fastApiClient.newCall(request).execute().use { response ->
                    val responseBody = response.body?.string() ?: throw Exception("Empty response body")
                    val json = org.json.JSONObject(responseBody)
                    val queued = response.code == 202 || json.optBoolean("queued", false)
                    if (queued) {
                        val jobId = json.optString("job_id", "")
                        if (jobId.isEmpty()) throw Exception("Missing job_id")
                        withContext(Dispatchers.Main) { organizerResult = "Đang sắp xếp..."; organizerScanResult = null }
                        val finalJson = pollSmartOrganizeJob(apiBase, jobId)
                        val finalStatus = finalJson.optString("status", "")
                        val movedCount = finalJson.optInt("moved_count", 0)
                        val errorCount = finalJson.optInt("error_count", 0)
                        val errorMessage = finalJson.optString("error", "")
                        withContext(Dispatchers.Main) {
                            organizerResult = when (finalStatus) {
                                "finished" -> "Hoàn tất — $movedCount tệp đã sắp xếp"
                                "finished_with_errors" -> "Hoàn tất — $movedCount tệp ($errorCount lỗi)"
                                else -> if (errorMessage.isNotEmpty()) errorMessage else "Smart Organizer thất bại"
                            }
                            if (finalStatus == "failed" || finalStatus == "aborted") { organizerError = organizerResult; organizerResult = null }
                            organizerScanResult = null
                        }
                    } else if (response.isSuccessful) {
                        withContext(Dispatchers.Main) { organizerResult = "Hoàn tất — ${json.optInt("moved_count", 0)} tệp"; organizerScanResult = null }
                    } else { throw Exception("Lỗi NAS: ${response.code}") }
                }
                }
            } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (e: Exception) { withContext(Dispatchers.Main) { organizerError = "Lỗi kết nối: ${e.message}" } }
            finally { withContext(Dispatchers.Main) { organizerExecuting = false } }
        }
    }

    private suspend fun pollSmartOrganizeJob(apiBase: String, jobId: String): org.json.JSONObject {
        var delayMs = 1000L; val deadline = System.currentTimeMillis() + 20 * 60 * 1000L
        while (System.currentTimeMillis() < deadline) {
            val request = okhttp3.Request.Builder().url("$apiBase/api/tools/smart_organize/status/$jobId").get().let(WebDavManager::tagCurrentAuth).build()
            NasApplication.instance.fastApiClient.newCall(request).execute().use { response ->
                val responseBody = response.body?.string()
                if (!response.isSuccessful || responseBody == null) throw Exception("Lỗi NAS: ${response.code}")
                val json = org.json.JSONObject(responseBody)
                when (json.optString("status", "")) {
                    "queued", "running" -> Unit
                    "finished", "finished_with_errors", "failed", "aborted" -> return json
                    else -> throw Exception("Trạng thái không hợp lệ")
                }
            }
            kotlinx.coroutines.delay(delayMs); delayMs = (delayMs * 2).coerceAtMost(5000L)
        }
        throw java.util.concurrent.TimeoutException("Smart organizer timed out")
    }

    fun organizeLegacyVideos() {
        organizingLegacyRunning = true
        organizingLegacyResult = null
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val apiBase = WebDavManager.currentBaseUrl.toApiBaseUrl()
                if (apiBase.isBlank()) {
                    withContext(Dispatchers.Main) {
                        organizingLegacyResult = "Chưa có địa chỉ NAS"
                    }
                    return@launch
                }
                val req = okhttp3.Request.Builder()
                    .url("$apiBase/api/tools/organize_legacy_videos")
                    .post(ByteArray(0).toRequestBody(null, 0, 0))
                    .build()
                NasApplication.instance.fastApiClient.newCall(req).execute().use { resp ->
                    val body = resp.body?.string() ?: "{}"
                    val json = org.json.JSONObject(body)
                    val ok = resp.isSuccessful && json.optBoolean("success", false)
                    val moved = json.optInt("moved_count", 0)
                    val errCount = json.optJSONArray("errors")?.length() ?: 0
                    val msg = if (ok) {
                        if (errCount > 0) "Đã di chuyển $moved video, $errCount lỗi" else "Đã di chuyển $moved video vào /Other Video/"
                    } else {
                        "Lỗi server: ${json.optString("message", body)}"
                    }
                    withContext(Dispatchers.Main) { organizingLegacyResult = msg }
                }
            } catch (e: kotlinx.coroutines.CancellationException) { throw e } catch (e: Exception) {
                withContext(Dispatchers.Main) {
                    organizingLegacyResult = "Lỗi: ${e.message}"
                }
            } finally {
                withContext(Dispatchers.Main) { organizingLegacyRunning = false }
            }
        }
    }
    fun resetOrganizingLegacy() { organizingLegacyRunning = false; organizingLegacyResult = null }
}